const $=id=>document.getElementById(id);let state=null;
const ASSETS=['CASHCAT','PONS','SKR','ZORA','FARTCOIN','PUMP','SPX','PEPE','BONK','WIF'];
const TARGETS=[0.05,0.1,0.15,0.2,0.5,1,2];
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
function priceFmt(n){if(!Number.isFinite(Number(n)))return'—';const v=Number(n);return`$${v.toLocaleString('en-US',{minimumFractionDigits:v>=100?2:4,maximumFractionDigits:v>=100?2:8})}`;}
const pct=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const cls=n=>Number(n)>0?'positive':Number(n)<0?'negative':'';
const clamp=(n,min=0,max=1)=>Math.max(min,Math.min(max,n));
const withdrawn=b=>Number(b.withdrawnCash||0);
const riskLabel=b=>Number(b.maxDrawdownPct||0)>-1?'GREEN':Number(b.maxDrawdownPct||0)>-3?'YELLOW':'RED';
function allBots(){return Object.values(state?.bots||{});}
function scoreBot(b){const bots=allBots();const maxW=Math.max(1,...bots.map(withdrawn));const maxH=Math.max(1,...bots.map(x=>Number(x.harvestCount||0)));const cashScore=clamp(withdrawn(b)/maxW);const harvestScore=clamp(Number(b.harvestCount||0)/maxH);const dd=Math.abs(Math.min(0,Number(b.maxDrawdownPct||0)));const riskScore=clamp(1-dd/5);const coverage=Number(b.activeWealth||0)>=Number(b.baseCapital||1000)?1:clamp(Number(b.activeWealth||0)/Number(b.baseCapital||1000));return Math.round((cashScore*.45+harvestScore*.20+riskScore*.20+coverage*.15)*100);}
function elapsedHours(b){return Number(b.elapsedHours||0);}
function perDay(b){const h=elapsedHours(b);return h>0?withdrawn(b)/h*24:0;}
function perWeek(b){return perDay(b)*7;}
function monthlyRunRate(b,capital){const h=elapsedHours(b);if(h<24)return null;return withdrawn(b)/h*24*30*(capital/Number(b.baseCapital||1000));}
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function renderTotals(){const bots=allBots(),capital=bots.reduce((s,b)=>s+Number(b.baseCapital||0),0),banked=bots.reduce((s,b)=>s+Number(b.bankedProfit||0),0),w=bots.reduce((s,b)=>s+withdrawn(b),0),active=bots.reduce((s,b)=>s+Number(b.activeWealth||0),0),econ=bots.reduce((s,b)=>s+Number(b.totalEconomicValue||0),0),hold=bots.reduce((s,b)=>s+Number(b.buyHoldValue||0),0),harvests=bots.reduce((s,b)=>s+Number(b.harvestCount||0),0);$('totalCapital').textContent=money(capital);$('totalBanked').textContent=money(banked);$('totalWithdrawn').textContent=money(w);$('activeWealth').textContent=money(active);$('economicValue').textContent=money(econ);$('buyHoldValue').textContent=money(hold);$('botVsHold').textContent=`${econ-hold>=0?'+':''}${money(econ-hold)} bot vs hold`;$('botVsHold').className=cls(econ-hold);$('totalHarvests').textContent=`${harvests} harvest${harvests===1?'':'s'}`;$('activePnL').textContent=`${active-capital>=0?'+':''}${money(active-capital)} active vs base`;$('activePnL').className=cls(active-capital);$('economicPnL').textContent=`${econ-capital>=0?'+':''}${money(econ-capital)} incl. withdrawn`;$('economicPnL').className=cls(econ-capital);}
function renderCashByCrypto(){const rows=ASSETS.map(s=>{const variants=TARGETS.map(t=>state.bots[botId(s,t)]).filter(Boolean);const best=[...variants].sort((a,b)=>withdrawn(b)-withdrawn(a)||scoreBot(b)-scoreBot(a)||Number(b.activeNet||0)-Number(a.activeNet||0))[0];return best?{...best,score:scoreBot(best)}:null;}).filter(Boolean).sort((a,b)=>withdrawn(b)-withdrawn(a)||b.score-a.score);$('cashCryptoBody').innerHTML=rows.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive">${money(b.withdrawnCash)}</td><td>${money(perDay(b))}</td><td>${money(perWeek(b))}</td><td>${money(b.activeWealth)}</td><td>${money(b.totalEconomicValue)}</td><td>${money(b.buyHoldValue)}</td><td class="${cls(b.botVsHold)}"><strong>${money(b.botVsHold)}</strong></td><td><strong>${b.score}</strong></td><td>${riskLabel(b)}</td></tr>`).join('');}
function renderCryptoTotals(){const rows=ASSETS.map(s=>{const g=TARGETS.map(t=>state.bots[botId(s,t)]).filter(Boolean);return{symbol:s,harvests:g.reduce((x,b)=>x+Number(b.harvestCount||0),0),banked:g.reduce((x,b)=>x+Number(b.bankedProfit||0),0),withdrawn:g.reduce((x,b)=>x+withdrawn(b),0),active:g.reduce((x,b)=>x+Number(b.activeWealth||0),0),econ:g.reduce((x,b)=>x+Number(b.totalEconomicValue||0),0),hold:g.reduce((x,b)=>x+Number(b.buyHoldValue||0),0),hours:Math.max(...g.map(elapsedHours),0)};}).sort((a,b)=>b.withdrawn-a.withdrawn);$('cryptoTotalsBody').innerHTML=rows.map((r,i)=>{const d=r.hours>0?r.withdrawn/r.hours*24:0;return`<tr><td>${i+1}</td><td><strong>${r.symbol}</strong></td><td>${r.harvests}</td><td class="positive">${money(r.withdrawn)}</td><td>${money(d)}</td><td>${money(d*7)}</td><td>${money(r.active)}</td><td>${money(r.econ)}</td><td>${money(r.hold)}</td><td class="${cls(r.econ-r.hold)}">${money(r.econ-r.hold)}</td></tr>`;}).join('');}
function renderCashBots(){const bots=allBots().map(b=>({...b,score:scoreBot(b)})).sort((a,b)=>withdrawn(b)-withdrawn(a)||b.score-a.score||Number(b.activeNet||0)-Number(a.activeNet||0));$('cashBotBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive"><strong>${money(b.withdrawnCash)}</strong></td><td>${money(perDay(b))}</td><td>${money(perWeek(b))}</td><td>${money(b.activeWealth)}</td><td>${money(b.totalEconomicValue)}</td><td>${money(b.buyHoldValue)}</td><td class="${cls(b.botVsHold)}"><strong>${money(b.botVsHold)}</strong></td><td><strong>${b.score}</strong></td><td>${riskLabel(b)}</td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td></tr>`).join('');}
function renderSalary(){const bots=allBots().map(b=>({...b,score:scoreBot(b)})).sort((a,b)=>withdrawn(b)-withdrawn(a)||b.score-a.score);const best=bots[0];if(!best){$('salaryBody').innerHTML='';return;}const capitals=[1000,5000,10000,25000,50000];const h=elapsedHours(best);$('salaryLead').textContent=`Leader now: ${best.symbol} ${best.targetPct}% • Withdrawn ${money(best.withdrawnCash)} • ${money(perDay(best))}/day • Score ${best.score}`;$('salaryBody').innerHTML=capitals.map(c=>{const m=monthlyRunRate(best,c);return`<tr><td>${money(c)}</td><td>${m===null?'Collecting data (<24h)':money(m)}</td></tr>`;}).join('');$('salaryNote').textContent=h<24?'Monthly run-rate unlocks after 24 hours. Daily and weekly pace are shown live but remain very noisy early on.':'Run-rate extrapolates actual withdrawn-cash pace observed so far. It is not a profit guarantee.';}
function renderTargetLeaders(){$('targetBody').innerHTML=TARGETS.map(t=>{const group=ASSETS.map(s=>state.bots[botId(s,t)]).filter(Boolean);const banked=group.reduce((s,b)=>s+Number(b.bankedProfit||0),0),w=group.reduce((s,b)=>s+withdrawn(b),0),active=group.reduce((s,b)=>s+Number(b.activeWealth||0),0),econ=group.reduce((s,b)=>s+Number(b.totalEconomicValue||0),0),hold=group.reduce((s,b)=>s+Number(b.buyHoldValue||0),0),harvests=group.reduce((s,b)=>s+Number(b.harvestCount||0),0),hours=Math.max(...group.map(elapsedHours),0),d=hours>0?w/hours*24:0;return`<tr><td><strong>${t}%</strong></td><td>${harvests}</td><td class="positive"><strong>${money(w)}</strong></td><td>${money(d)}</td><td>${money(d*7)}</td><td>${money(active)}</td><td>${money(econ)}</td><td>${money(hold)}</td><td class="${cls(econ-hold)}">${money(econ-hold)}</td></tr>`;}).join('');}
function renderScoreboard(){const bots=allBots().sort((a,b)=>Number(b.totalEconomicValue||0)-Number(a.totalEconomicValue||0));$('scoreBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${priceFmt(b.currentPrice)}</td><td>${b.harvestCount}</td><td class="positive">${money(b.withdrawnCash)}</td><td>${money(perDay(b))}</td><td>${money(b.cashBalance)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td>${money(b.activeWealth)}</td><td>${money(b.totalEconomicValue)}</td><td>${money(b.buyHoldValue)}</td><td class="${cls(b.botVsHold)}">${money(b.botVsHold)}</td><td>${scoreBot(b)}</td><td>${riskLabel(b)}</td></tr>`).join('');}
function render(){if(!state?.bots)return;renderTotals();renderCashByCrypto();renderCryptoTotals();renderCashBots();renderSalary();renderTargetLeaders();renderScoreboard();const bots=allBots(),errors=bots.filter(b=>b.lastError);$('liveDot').className=`dot ${errors.length?'':'live'}`;$('liveStatus').textContent=errors.length?`Price feed issue: ${[...new Set(errors.map(b=>b.symbol))].join(', ')}`:'70 paper bots live • 7 targets × 10 assets • server 24/7';}
async function refreshState(){try{state=await api('/api/state');render();}catch(e){$('liveDot').className='dot';$('liveStatus').textContent='Server connection lost';}}
$('refreshBtn').addEventListener('click',async()=>{$('refreshBtn').disabled=true;try{state=await api('/api/refresh',{method:'POST',body:'{}'});render();}finally{$('refreshBtn').disabled=false;}});refreshState();setInterval(refreshState,5000);
