const http=require('http'),fs=require('fs'),path=require('path');
const PORT=process.env.PORT||3000;
const STATE_FILE=process.env.STATE_FILE||path.join(__dirname,'paper-state-70bots.json');
const POLL_MS=Math.max(10000,Number(process.env.POLL_MS||15000));
const ASSETS={CASHCAT:'cash-cat',PONS:'pons',SKR:'seeker',ZORA:'zora',FARTCOIN:'fartcoin',PUMP:'pump-fun',SPX:'spx6900',PEPE:'pepe',BONK:'bonk',WIF:'dogwifcoin'};
const TARGETS=[0.05,0.1,0.15,0.2,0.5,1,2];
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
function freshBot(symbol,targetPct){return{id:botId(symbol,targetPct),symbol,coinId:ASSETS[symbol],baseCapital:1000,targetPct,feePct:0,currentPrice:null,entryPrice:null,benchmarkStartPrice:null,tokensHeld:0,bankedProfit:0,withdrawnCash:0,withdrawalCount:0,harvestCount:0,running:true,startedAt:null,lastHarvestAt:null,lastWithdrawalAt:null,lastUpdated:null,lastError:null,maxDrawdownPct:0,history:[],withdrawalHistory:[]};}
function defaults(){const bots={};for(const s of Object.keys(ASSETS))for(const t of TARGETS){const b=freshBot(s,t);bots[b.id]=b;}return{bots};}
function load(){try{if(fs.existsSync(STATE_FILE)){const saved=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));if(saved.bots){const bots={};for(const s of Object.keys(ASSETS))for(const t of TARGETS){const f=freshBot(s,t),p=saved.bots[f.id];if(p){const hist=Array.isArray(p.history)?p.history:[];const benchmarkStartPrice=Number(p.benchmarkStartPrice||hist[0]?.entry||p.entryPrice||0)||null;bots[f.id]={...f,...p,id:f.id,symbol:s,coinId:f.coinId,targetPct:t,benchmarkStartPrice,withdrawnCash:Number(p.withdrawnCash||0),withdrawalCount:Number(p.withdrawalCount||0),withdrawalHistory:Array.isArray(p.withdrawalHistory)?p.withdrawalHistory:[]};}else bots[f.id]=f;}return{bots};}}}catch(e){console.error('State load failed',e.message);}return defaults();}
let state=load();
function save(){try{fs.writeFileSync(STATE_FILE,JSON.stringify(state,null,2));}catch(e){console.error('State save failed',e.message);}}
const positionValue=b=>b.tokensHeld&&b.currentPrice?b.tokensHeld*b.currentPrice:0;
const cashBalance=b=>Math.max(0,Number(b.bankedProfit||0)-Number(b.withdrawnCash||0));
const targetPrice=b=>b.entryPrice?b.entryPrice*(1+b.targetPct/100):null;
function autoWithdraw(b){if(!b.entryPrice)return;const pos=positionValue(b),cash=cashBalance(b),activeWealth=pos+cash,amount=Math.max(0,Math.min(cash,activeWealth-b.baseCapital));if(amount>0.000001){const now=new Date().toISOString();b.withdrawnCash+=amount;b.withdrawalCount++;b.lastWithdrawalAt=now;b.withdrawalHistory.push({number:b.withdrawalCount,time:now,amount,totalWithdrawn:b.withdrawnCash,activeWealthBefore:activeWealth,activeWealthAfter:activeWealth-amount});}}
function evaluate(b){if(!b.running||!b.currentPrice)return;if(!b.entryPrice){b.entryPrice=b.currentPrice;b.benchmarkStartPrice=b.benchmarkStartPrice||b.currentPrice;b.tokensHeld=b.baseCapital/b.entryPrice;b.startedAt=b.startedAt||new Date().toISOString();autoWithdraw(b);return;}b.benchmarkStartPrice=b.benchmarkStartPrice||b.entryPrice;const move=((b.currentPrice/b.entryPrice)-1)*100;if(move<b.maxDrawdownPct)b.maxDrawdownPct=move;if(b.currentPrice+Number.EPSILON>=targetPrice(b)){const exitValue=positionValue(b),grossProfit=exitValue-b.baseCapital,fees=(b.baseCapital+exitValue)*(b.feePct/100),netBanked=grossProfit-fees,now=new Date().toISOString();b.bankedProfit+=netBanked;b.harvestCount++;b.lastHarvestAt=now;b.history.push({number:b.harvestCount,time:now,entry:b.entryPrice,exit:b.currentPrice,grossProfit,fees,netBanked,totalBanked:b.bankedProfit});b.entryPrice=b.currentPrice;b.tokensHeld=b.baseCapital/b.entryPrice;}autoWithdraw(b);}
async function fetchPrices(){const ids=Object.values(ASSETS).join(',');const url=`https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent(ids)}&vs_currencies=usd`;const res=await fetch(url,{headers:{'accept':'application/json','user-agent':'meme-harvest-70/1.0'}});if(!res.ok)throw new Error(`CoinGecko HTTP ${res.status}`);return res.json();}
async function fetchAll(){let data;try{data=await fetchPrices();}catch(e){for(const b of Object.values(state.bots)){b.lastError=e.message;b.lastUpdated=new Date().toISOString();}save();return;}for(const [symbol,coinId] of Object.entries(ASSETS)){const price=Number(data?.[coinId]?.usd);for(const t of TARGETS){const b=state.bots[botId(symbol,t)];if(Number.isFinite(price)&&price>0){b.currentPrice=price;b.lastError=null;evaluate(b);}else b.lastError=`${symbol}/USD price missing`;b.lastUpdated=new Date().toISOString();}}save();}
function pub(b){const pos=positionValue(b),cash=cashBalance(b),cycleMovePct=b.entryPrice&&b.currentPrice?((b.currentPrice/b.entryPrice)-1)*100:0,target=targetPrice(b),activeWealth=(b.entryPrice?pos:b.baseCapital)+cash,activeNet=activeWealth-b.baseCapital,totalEconomicValue=activeWealth+Number(b.withdrawnCash||0),economicNet=totalEconomicValue-b.baseCapital,withdrawableNow=Math.max(0,Math.min(cash,activeNet)),benchmarkStart=Number(b.benchmarkStartPrice||b.entryPrice||0),buyHoldValue=benchmarkStart&&b.currentPrice?b.baseCapital*(b.currentPrice/benchmarkStart):b.baseCapital,buyHoldNet=buyHoldValue-b.baseCapital,botVsHold=totalEconomicValue-buyHoldValue,elapsedHours=b.startedAt?Math.max(0,(Date.now()-new Date(b.startedAt).getTime())/36e5):0;return{...b,targetPrice:target,positionValue:pos,cashBalance:cash,unrealized:b.entryPrice?pos-b.baseCapital:0,cycleMovePct,distancePct:target&&b.currentPrice?((target/b.currentPrice)-1)*100:null,activeWealth,activeNet,withdrawableNow,totalEconomicValue,economicNet,economicNetPct:(economicNet/b.baseCapital)*100,totalWealth:totalEconomicValue,netResult:economicNet,netResultPct:(economicNet/b.baseCapital)*100,buyHoldValue,buyHoldNet,botVsHold,elapsedHours};}
const publicState=()=>({assets:Object.keys(ASSETS),targets:TARGETS,bots:Object.fromEntries(Object.entries(state.bots).map(([id,b])=>[id,pub(b)]))});
function sendJson(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(body);}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname==='/api/health')return sendJson(res,200,{ok:true,botCount:Object.keys(state.bots).length,bots:Object.values(state.bots).map(b=>({id:b.id,running:b.running,lastUpdated:b.lastUpdated,lastError:b.lastError}))});if(url.pathname==='/api/state'&&req.method==='GET')return sendJson(res,200,publicState());if(url.pathname==='/api/refresh'&&req.method==='POST'){await fetchAll();return sendJson(res,200,publicState());}let urlPath=url.pathname==='/'?'index.html':url.pathname.replace(/^[/\\]+/,'');const safePath=path.normalize(urlPath).replace(/^([.][.][/\\])+/,'');const filePath=path.join(__dirname,safePath);if(!filePath.startsWith(__dirname)){res.writeHead(403);return res.end('Forbidden');}fs.readFile(filePath,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':mime[path.extname(filePath)]||'application/octet-stream'});res.end(data);});}catch(e){sendJson(res,500,{error:e.message});}});
server.listen(PORT,()=>console.log(`Meme Harvest 70 Lab • 70 bots listening on ${PORT}`));fetchAll();setInterval(fetchAll,POLL_MS);
