const $=id=>document.getElementById(id);let state=null;
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
function priceFmt(n){if(!Number.isFinite(Number(n)))return '—';const v=Number(n);return `$${v.toLocaleString('en-US',{minimumFractionDigits:v>=100?2:4,maximumFractionDigits:v>=100?2:8})}`;}
function pct(n){const v=Number(n||0);return `${v>=0?'+':''}${v.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')}%`;}
function targetFmt(n){return `${Number(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}%`;}
function pnlClass(n){return Number(n)>0?'positive':Number(n)<0?'negative':'';}
async function api(path,options={}){const res=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json();}
function targetCard(b){return `<article class="panel"><div class="panel-head"><div><p class="eyebrow">${b.symbol} • ${targetFmt(b.targetPct)} TARGET</p><h2>${b.symbol} ${targetFmt(b.targetPct)} Bot</h2></div><span class="badge ${b.running?'on':'off'}">${b.running?'RUNNING':'PAUSED'}</span></div><div class="grid stats lower"><article class="card accent"><span>Live price</span><strong>${priceFmt(b.currentPrice)}</strong><small>${b.lastError?b.lastError:'Kraken live'}</small></article><article class="card"><span>Cycle entry</span><strong>${priceFmt(b.entryPrice)}</strong><small class="${pnlClass(b.cycleMovePct)}">${pct(b.cycleMovePct)}</small></article><article class="card profit"><span>Banked profit</span><strong>${money(b.bankedProfit)}</strong><small>${b.harvestCount} harvests</small></article><article class="card"><span>Net result</span><strong class="${pnlClass(b.netResult)}">${money(b.netResult)}</strong><small>Banked + unrealized</small></article></div></article>`;}
function renderTotals(){const bots=Object.values(state.bots),capital=bots.reduce((s,b)=>s+Number(b.baseCapital||0),0),banked=bots.reduce((s,b)=>s+Number(b.bankedProfit||0),0),positions=bots.reduce((s,b)=>s+Number(b.positionValue||0),0),wealth=bots.reduce((s,b)=>s+Number(b.totalWealth||0),0),harvests=bots.reduce((s,b)=>s+Number(b.harvestCount||0),0),pnl=wealth-capital;$('totalCapital').textContent=money(capital);$('totalBanked').textContent=money(banked);$('totalPositions').textContent=money(positions);$('totalWealth').textContent=money(wealth);$('totalHarvests').textContent=`${harvests} harvest${harvests===1?'':'s'} • tap for details`;$('totalPnL').textContent=`${pnl>=0?'+':''}${money(pnl)} vs base`;$('totalPnL').className=pnlClass(pnl);}
function renderRanking(){const ranked=Object.values(state.bots).sort((a,b)=>Number(b.harvestCount)-Number(a.harvestCount)||Number(b.bankedProfit)-Number(a.bankedProfit));$('rankBody').innerHTML=ranked.map((b,i)=>`<tr><td><strong>#${i+1}</strong></td><td><strong>${b.symbol}</strong></td><td><strong>${targetFmt(b.targetPct)}</strong></td><td><strong>${b.harvestCount}</strong></td><td class="positive"><strong>${money(b.bankedProfit)}</strong></td></tr>`).join('');}
function renderScoreboard(){const rows=[];for(const s of state.assets)for(const t of state.targets){const b=state.bots[botId(s,t)];rows.push(`<tr><td><strong>${s}</strong></td><td><strong>${targetFmt(t)}</strong></td><td>${priceFmt(b.currentPrice)}</td><td>${money(b.baseCapital)}</td><td class="${pnlClass(b.cycleMovePct)}">${pct(b.cycleMovePct)}</td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${pnlClass(b.unrealized)}">${money(b.unrealized)}</td><td class="${pnlClass(b.netResult)}"><strong>${money(b.netResult)}</strong></td><td>${money(b.totalWealth)}</td></tr>`);} $('scoreBody').innerHTML=rows.join('');}
function renderWinners(){$('winnerBody').innerHTML=state.assets.map(s=>{const variants=state.targets.map(t=>state.bots[botId(s,t)]),best=[...variants].sort((a,b)=>Number(b.harvestCount)-Number(a.harvestCount)||Number(b.bankedProfit)-Number(a.bankedProfit))[0];return `<tr><td><strong>${s}</strong></td><td><strong>${targetFmt(best.targetPct)}</strong></td><td><strong>${best.harvestCount}</strong></td><td class="positive">${money(best.bankedProfit)}</td><td class="${pnlClass(best.netResult)}">${money(best.netResult)}</td></tr>`;}).join('');}
function buildHarvestBreakdown(){if(!state?.bots)return;const contributors=Object.values(state.bots).filter(b=>Number(b.harvestCount)>0).sort((a,b)=>Number(b.harvestCount)-Number(a.harvestCount)||Number(b.bankedProfit)-Number(a.bankedProfit));const total=contributors.reduce((s,b)=>s+Number(b.harvestCount||0),0),profit=contributors.reduce((s,b)=>s+Number(b.bankedProfit||0),0);$('harvestModalSummary').textContent=`${total} total harvest${total===1?'':'s'} • ${money(profit)} total banked • ${contributors.length} contributing bot test${contributors.length===1?'':'s'}.`;$('harvestBreakdownBody').innerHTML=contributors.length?contributors.map(b=>{const count=Number(b.harvestCount||0),banked=Number(b.bankedProfit||0),avg=count>0?banked/count:0,profitPct=Number(b.baseCapital)>0?banked/Number(b.baseCapital)*100:0;return `<tr><td data-label="Asset"><strong>${b.symbol}</strong></td><td data-label="Target"><strong>${targetFmt(b.targetPct)}</strong></td><td data-label="Times"><strong>${count}</strong></td><td data-label="Avg / harvest" class="positive"><strong>${money(avg)}</strong></td><td data-label="Total banked" class="positive"><strong>${money(banked)}</strong></td><td data-label="Total profit %" class="positive"><strong>${pct(profitPct)}</strong></td></tr>`;}).join(''):`<tr class="empty"><td colspan="6">No harvests yet.</td></tr>`;}
function openHarvestModal(){buildHarvestBreakdown();$('harvestModal').hidden=false;document.body.classList.add('modal-open');$('closeHarvestModal').focus();}
function closeHarvestModal(){$('harvestModal').hidden=true;document.body.classList.remove('modal-open');}
function render(){if(!state?.bots)return;renderTotals();renderRanking();renderScoreboard();renderWinners();if(!$('harvestModal').hidden)buildHarvestBreakdown();$('botsGrid').innerHTML=state.assets.map(s=>state.targets.map(t=>targetCard(state.bots[botId(s,t)])).join('')).join('');const bots=Object.values(state.bots),errors=bots.filter(b=>b.lastError),errorAssets=[...new Set(errors.map(b=>b.symbol))];$('liveDot').className=`dot ${errors.length?'':'live'}`;$('liveStatus').textContent=errors.length?`Feed issue on ${errorAssets.join(', ')}`:`${state.botCount} paper bots live • ${state.assets.length} assets • server 24/7`;}
async function refreshState(){try{state=await api('/api/state');render();}catch(e){$('liveDot').className='dot';$('liveStatus').textContent='Server connection lost';}}
$('refreshBtn').addEventListener('click',async()=>{$('refreshBtn').disabled=true;try{state=await api('/api/refresh',{method:'POST',body:'{}'});render();}finally{$('refreshBtn').disabled=false;}});
$('totalHarvests').addEventListener('click',e=>{e.stopPropagation();openHarvestModal();});
$('totalProfitCard').addEventListener('click',openHarvestModal);$('totalProfitCard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openHarvestModal();}});
$('closeHarvestModal').addEventListener('click',closeHarvestModal);$('harvestModal').addEventListener('click',e=>{if(e.target===$('harvestModal'))closeHarvestModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('harvestModal').hidden)closeHarvestModal();});
$('backToTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
refreshState();setInterval(refreshState,5000);