const $=id=>document.getElementById(id);let state=null;
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
function priceFmt(n){if(!Number.isFinite(Number(n)))return '—';const v=Number(n);return `$${v.toLocaleString('en-US',{minimumFractionDigits:v>=100?2:4,maximumFractionDigits:v>=100?2:8})}`;}
function pct(n){const v=Number(n||0);return `${v>=0?'+':''}${v.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')}%`;}
function targetFmt(n){return `${Number(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2})}%`;}
function pnlClass(n){return Number(n)>0?'positive':Number(n)<0?'negative':'';}
async function api(path,options={}){const res=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json();}
function targetCard(b){return `<article class="panel"><div class="panel-head"><div><p class="eyebrow">${b.symbol} • ${targetFmt(b.targetPct)} TARGET</p><h2>${b.symbol} ${targetFmt(b.targetPct)} Bot</h2></div><span class="badge ${b.running?'on':'off'}">${b.running?'RUNNING':'PAUSED'}</span></div><div class="grid stats lower"><article class="card accent"><span>Live price</span><strong>${priceFmt(b.currentPrice)}</strong><small>${b.lastError?b.lastError:'Kraken live'}</small></article><article class="card"><span>Cycle entry</span><strong>${priceFmt(b.entryPrice)}</strong><small class="${pnlClass(b.cycleMovePct)}">${pct(b.cycleMovePct)}</small></article><article class="card profit"><span>Banked profit</span><strong>${money(b.bankedProfit)}</strong><small>${b.harvestCount} harvests</small></article><article class="card"><span>Net result</span><strong class="${pnlClass(b.netResult)}">${money(b.netResult)}</strong><small>Banked + unrealized</small></article></div><div class="formula"><strong>Current position</strong><p>${money(b.positionValue)} • Unrealized <span class="${pnlClass(b.unrealized)}">${money(b.unrealized)}</span> • Total wealth ${money(b.totalWealth)}</p></div></article>`;}
function renderTotals(){const bots=Object.values(state.bots),capital=bots.reduce((s,b)=>s+Number(b.baseCapital||0),0),banked=bots.reduce((s,b)=>s+Number(b.bankedProfit||0),0),positions=bots.reduce((s,b)=>s+Number(b.positionValue||0),0),wealth=bots.reduce((s,b)=>s+Number(b.totalWealth||0),0),harvests=bots.reduce((s,b)=>s+Number(b.harvestCount||0),0),pnl=wealth-capital;$('totalCapital').textContent=money(capital);$('totalBanked').textContent=money(banked);$('totalPositions').textContent=money(positions);$('totalWealth').textContent=money(wealth);$('totalHarvests').textContent=`${harvests} harvest${harvests===1?'':'s'}`;$('totalPnL').textContent=`${pnl>=0?'+':''}${money(pnl)} vs base`;$('totalPnL').className=pnlClass(pnl);}
function renderScoreboard(){const rows=[];for(const s of state.assets)for(const t of state.targets){const b=state.bots[botId(s,t)];rows.push(`<tr><td><strong>${s}</strong></td><td><strong>${targetFmt(t)}</strong></td><td>${priceFmt(b.currentPrice)}</td><td>${money(b.baseCapital)}</td><td class="${pnlClass(b.cycleMovePct)}">${pct(b.cycleMovePct)}</td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${pnlClass(b.unrealized)}">${money(b.unrealized)}</td><td class="${pnlClass(b.netResult)}"><strong>${money(b.netResult)}</strong></td><td>${money(b.totalWealth)}</td></tr>`);} $('scoreBody').innerHTML=rows.join('');}
function renderWinners(){$('winnerBody').innerHTML=state.assets.map(s=>{const variants=state.targets.map(t=>state.bots[botId(s,t)]),best=[...variants].sort((a,b)=>Number(b.netResult)-Number(a.netResult))[0];return `<tr><td><strong>${s}</strong></td><td><strong>${targetFmt(best.targetPct)}</strong></td><td>${best.harvestCount}</td><td class="positive">${money(best.bankedProfit)}</td><td class="${pnlClass(best.netResult)}"><strong>${money(best.netResult)}</strong></td></tr>`;}).join('');}
function render(){if(!state?.bots)return;renderTotals();renderScoreboard();renderWinners();$('botsGrid').innerHTML=state.assets.map(s=>state.targets.map(t=>targetCard(state.bots[botId(s,t)])).join('')).join('');const bots=Object.values(state.bots),errors=bots.filter(b=>b.lastError),errorAssets=[...new Set(errors.map(b=>b.symbol))];$('liveDot').className=`dot ${errors.length?'':'live'}`;$('liveStatus').textContent=errors.length?`Feed issue on ${errorAssets.join(', ')}`:`${state.botCount} paper bots live • ${state.assets.length} assets • server 24/7`;}
async function refreshState(){try{state=await api('/api/state');render();}catch(e){$('liveDot').className='dot';$('liveStatus').textContent='Server connection lost';console.error(e);}}
$('refreshBtn').addEventListener('click',async()=>{$('refreshBtn').disabled=true;try{state=await api('/api/refresh',{method:'POST',body:'{}'});render();}finally{$('refreshBtn').disabled=false;}});
refreshState();setInterval(refreshState,5000);
