const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||3000);
const SYMBOL='TRUMPUSDT';
const CAPITAL=Number(process.env.CAPITAL_USDT||250);
const TARGET_PCT=Number(process.env.TARGET_PCT||0.5);
const FEE_PCT=Number(process.env.SPOT_FEE_PCT||0.1);
const MIN_ORDER_USDT=Number(process.env.MIN_ORDER_USDT||1.02);
const POLL_MS=Math.max(5000,Number(process.env.POLL_MS||5000));
const STATE_FILE=process.env.STATE_FILE||path.join(__dirname,'state.json');
function round(x,n=6){return Number(Number(x).toFixed(n));}
function fresh(){return{mode:'ACTIVE_PAPER_TEST',symbol:SYMBOL,capitalUsdt:CAPITAL,targetPct:TARGET_PCT,feePct:FEE_PCT,minOrderUsdt:MIN_ORDER_USDT,startedAt:null,lastUpdated:null,lastPrice:null,startPrice:null,anchorPrice:null,highPrice:null,lowPrice:null,previousPrice:null,tokensHeld:0,harvestCount:0,grossHarvestedUsdt:0,feesPaidUsdt:0,netHarvestedUsdt:0,lastHarvest:null,history:[],lastError:null,ticks:0,feedSource:null};}
function load(){try{if(fs.existsSync(STATE_FILE)){const saved=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));return{...fresh(),...saved,mode:'ACTIVE_PAPER_TEST'};}}catch(e){console.error('State load failed:',e.message);}return fresh();}
let state=load();
function save(){try{fs.writeFileSync(STATE_FILE,JSON.stringify(state,null,2));}catch(e){console.error('State save failed:',e.message);}}
async function fetchJson(url){const r=await fetch(url,{headers:{'user-agent':'trump-250-active-sim/1.0','accept':'application/json'}});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${text.slice(0,80)}`);try{return JSON.parse(text);}catch{throw new Error(`Non-JSON response: ${text.slice(0,80)}`);}}
async function fetchBybit(){const t=await fetchJson('https://api.bybit.com/v5/market/tickers?category=spot&symbol=TRUMPUSDT');if(t.retCode!==0)throw new Error(t.retMsg||'Bybit ticker error');const row=t.result?.list?.[0]||{};const price=Number(row.lastPrice);if(!Number.isFinite(price)||price<=0)throw new Error('Bybit TRUMP price unavailable');return{price,minOrderAmt:MIN_ORDER_USDT,feedSource:'Bybit TRUMP/USDT'};}
async function fetchKraken(){const j=await fetchJson('https://api.kraken.com/0/public/Ticker?pair=TRUMPUSD');if(Array.isArray(j.error)&&j.error.length)throw new Error(j.error.join(', '));const row=Object.values(j.result||{})[0];const price=Number(row?.c?.[0]);if(!Number.isFinite(price)||price<=0)throw new Error('Kraken TRUMP price unavailable');return{price,minOrderAmt:MIN_ORDER_USDT,feedSource:'Kraken TRUMP/USD fallback'};}
async function fetchMarket(){try{return await fetchBybit();}catch(bybitErr){try{return await fetchKraken();}catch(krakenErr){throw new Error(`Bybit: ${bybitErr.message} | Kraken: ${krakenErr.message}`);}}}
function positionValue(){return state.tokensHeld*(state.lastPrice||0);}
function initialize(price){const now=new Date().toISOString();state.startedAt=state.startedAt||now;state.lastUpdated=now;state.lastPrice=price;state.previousPrice=price;state.startPrice=state.startPrice||price;state.anchorPrice=state.anchorPrice||price;state.highPrice=state.highPrice||price;state.lowPrice=state.lowPrice||price;state.tokensHeld=state.tokensHeld||CAPITAL/price;state.ticks=Number(state.ticks||0)+1;}
function evaluate(price,minOrderAmt){const now=new Date().toISOString();state.previousPrice=state.lastPrice||price;state.lastPrice=price;state.lastUpdated=now;state.minOrderUsdt=Math.max(MIN_ORDER_USDT,minOrderAmt||0);state.highPrice=Math.max(Number(state.highPrice||price),price);state.lowPrice=Math.min(Number(state.lowPrice||price),price);state.ticks=Number(state.ticks||0)+1;if(!state.anchorPrice||!state.tokensHeld){initialize(price);return;}const trigger=state.anchorPrice*(1+TARGET_PCT/100);const value=positionValue();const grossExcess=Math.max(0,value-CAPITAL);if(price+Number.EPSILON>=trigger&&grossExcess+1e-12>=state.minOrderUsdt){const fee=grossExcess*(FEE_PCT/100);const net=grossExcess-fee;const soldTokens=grossExcess/price;state.tokensHeld=Math.max(0,state.tokensHeld-soldTokens);state.harvestCount++;state.grossHarvestedUsdt+=grossExcess;state.feesPaidUsdt+=fee;state.netHarvestedUsdt+=net;state.lastHarvest={number:state.harvestCount,time:now,price:round(price,8),gross:round(grossExcess,6),fee:round(fee,6),net:round(net,6)};state.history.push(state.lastHarvest);if(state.history.length>500)state.history=state.history.slice(-500);state.anchorPrice=price;}}
async function tick(){try{const m=await fetchMarket();state.feedSource=m.feedSource;if(!state.startedAt)initialize(m.price);else evaluate(m.price,m.minOrderAmt);state.lastError=null;}catch(e){state.lastError=e.message;state.lastUpdated=new Date().toISOString();console.error('Tick error:',e.message);}save();}
function view(){const value=state.lastPrice?positionValue():CAPITAL;const unrealized=value-CAPITAL;const nextTarget=state.anchorPrice?state.anchorPrice*(1+TARGET_PCT/100):null;const elapsedMs=state.startedAt?Math.max(0,Date.now()-new Date(state.startedAt).getTime()):0;const elapsedHours=elapsedMs/36e5;const startMovePct=state.startPrice&&state.lastPrice?((state.lastPrice/state.startPrice)-1)*100:0;const cycleMovePct=state.anchorPrice&&state.lastPrice?((state.lastPrice/state.anchorPrice)-1)*100:0;const progressPct=TARGET_PCT>0?Math.max(0,Math.min(100,(cycleMovePct/TARGET_PCT)*100)):0;const tickMovePct=state.previousPrice&&state.lastPrice?((state.lastPrice/state.previousPrice)-1)*100:0;return{...state,active:true,positionValueUsdt:round(value,6),unrealizedUsdt:round(unrealized,6),nextTargetPrice:nextTarget?round(nextTarget,8):null,distanceToTargetPct:state.lastPrice&&nextTarget?round(((nextTarget/state.lastPrice)-1)*100,4):null,startMovePct:round(startMovePct,4),cycleMovePct:round(cycleMovePct,4),cycleProgressPct:round(progressPct,2),tickMovePct:round(tickMovePct,5),totalEconomicValueUsdt:round(value+state.netHarvestedUsdt,6),elapsedSeconds:Math.floor(elapsedMs/1000),elapsedHours:round(elapsedHours,3),harvestsPerHour:elapsedHours?round(state.harvestCount/elapsedHours,3):0,netPerHourUsdt:elapsedHours?round(state.netHarvestedUsdt/elapsedHours,4):0,pollMs:POLL_MS};}
function send(res,code,obj,type='application/json; charset=utf-8'){const body=type.startsWith('application/json')?JSON.stringify(obj):obj;res.writeHead(code,{'content-type':type,'cache-control':'no-store, no-cache, must-revalidate, proxy-revalidate','pragma':'no-cache','expires':'0'});res.end(body);}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/state')return send(res,200,view());if(u.pathname==='/api/health')return send(res,state.lastError?503:200,{ok:!state.lastError,active:true,mode:'ACTIVE_PAPER_TEST',feedSource:state.feedSource,lastPrice:state.lastPrice,lastUpdated:state.lastUpdated,lastError:state.lastError});if(u.pathname==='/')return fs.readFile(path.join(__dirname,'index.html'),'utf8',(e,d)=>e?send(res,500,'Error','text/plain'):send(res,200,d,'text/html; charset=utf-8'));return send(res,404,{error:'Not found'});});
server.listen(PORT,()=>console.log(`TRUMP $250 active simulator on ${PORT}; polling every ${POLL_MS}ms`));tick();setInterval(tick,POLL_MS);
