const $=id=>document.getElementById(id);let state=null;
const ASSETS=['TRUMP','WIF','PENGU','BONK','DOGE','SOL','XRP','ADA','LINK','ETH','BTC','PAXG'];
const TARGETS=[0.2,0.5,1,2];
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
function priceFmt(n){if(!Number.isFinite(Number(n)))return'—';const v=Number(n);return`$${v.toLocaleString('en-US',{minimumFractionDigits:v>=100?2:4,maximumFractionDigits:v>=100?2:8})}`;}
const pct=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const cls=n=>Number(n)>0?'positive':Number(n)<0?'negative':'';
const safeCash=b=>Math.max(0,Math.min(Number(b.bankedProfit||0),Number(b.netResult||0)));
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function renderTotals(){const bots=Object.values(state.bots),capital=bots.reduce((s,b)=>s+Number(b.baseCapital||0),0),banked=bots.reduce((s,b)=>s+Number(b.bankedProfit||0),0),wealth=bots.reduce((s,b)=>s+Number(b.totalWealth||0),0),safe=bots.reduce((s,b)=>s+safeCash(b),0),harvests=bots.reduce((s,b)=>s+Number(b.harvestCount||0),0),net=wealth-capital;$('totalCapital').textContent=money(capital);$('totalBanked').textContent=money(banked);$('totalSafeCash').textContent=money(safe);$('totalWealth').textContent=money(wealth);$('totalHarvests').textContent=`${harvests} harvest${harvests===1?'':'s'}`;$('totalPnL').textContent=`${net>=0?'+':''}${money(net)} vs base`;$('totalPnL').className=cls(net);}
function renderWinners(){$('winnerBody').innerHTML=ASSETS.map(s=>{const variants=TARGETS.map(t=>state.bots[botId(s,t)]);const best=[...variants].sort((a,b)=>b.netResult-a.netResult)[0];return`<tr><td><strong>${s}</strong></td><td><strong>${best.targetPct}%</strong></td><td>${best.harvestCount}</td><td class="positive">${money(best.bankedProfit)}</td><td class="${cls(best.netResult)}"><strong>${money(best.netResult)}</strong></td><td class="${cls(best.maxDrawdownPct)}">${pct(best.maxDrawdownPct)}</td></tr>`;}).join('');}
function renderCashByCrypto(){const rows=ASSETS.map(s=>{const variants=TARGETS.map(t=>state.bots[botId(s,t)]);const best=[...variants].sort((a,b)=>safeCash(b)-safeCash(a)||b.netResult-a.netResult||b.maxDrawdownPct-a.maxDrawdownPct)[0];return{...best,safe:safeCash(best)};}).sort((a,b)=>b.safe-a.safe||b.netResult-a.netResult);$('cashCryptoBody').innerHTML=rows.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}">${money(b.netResult)}</td><td class="positive"><strong>${money(b.safe)}</strong></td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td></tr>`).join('');}
function renderCashBots(){const bots=Object.values(state.bots).map(b=>({...b,safe:safeCash(b)})).sort((a,b)=>b.safe-a.safe||b.netResult-a.netResult||b.maxDrawdownPct-a.maxDrawdownPct);$('cashBotBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}">${money(b.netResult)}</td><td class="positive"><strong>${money(b.safe)}</strong></td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td></tr>`).join('');}
function renderTargetLeaders(){$('targetBody').innerHTML=TARGETS.map(t=>{const group=ASSETS.map(s=>state.bots[botId(s,t)]);const net=group.reduce((s,b)=>s+b.netResult,0),banked=group.reduce((s,b)=>s+b.bankedProfit,0),safe=group.reduce((s,b)=>s+safeCash(b),0),harvests=group.reduce((s,b)=>s+b.harvestCount,0);return`<tr><td><strong>${t}%</strong></td><td>${harvests}</td><td class="positive">${money(banked)}</td><td class="positive"><strong>${money(safe)}</strong></td><td class="${cls(net)}"><strong>${money(net)}</strong></td></tr>`;}).join('');}
function renderScoreboard(){const bots=Object.values(state.bots).sort((a,b)=>b.netResult-a.netResult);$('scoreBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${priceFmt(b.currentPrice)}</td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}"><strong>${money(b.netResult)}</strong></td><td class="positive"><strong>${money(safeCash(b))}</strong></td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td><td>${money(b.totalWealth)}</td></tr>`).join('');}
function render(){if(!state?.bots)return;renderTotals();renderWinners();renderCashByCrypto();renderCashBots();renderTargetLeaders();renderScoreboard();const bots=Object.values(state.bots),errors=bots.filter(b=>b.lastError);$('liveDot').className=`dot ${errors.length?'':'live'}`;$('liveStatus').textContent=errors.length?`Kraken issue: ${[...new Set(errors.map(b=>b.symbol))].join(', ')}`:'48 paper bots live • 12 Kraken feeds • server 24/7';}
async function refreshState(){try{state=await api('/api/state');render();}catch(e){$('liveDot').className='dot';$('liveStatus').textContent='Server connection lost';}}
$('refreshBtn').addEventListener('click',async()=>{$('refreshBtn').disabled=true;try{state=await api('/api/refresh',{method:'POST',body:'{}'});render();}finally{$('refreshBtn').disabled=false;}});refreshState();setInterval(refreshState,5000);
