const $=id=>document.getElementById(id);let state=null;
const ASSETS=['TRUMP','WIF','PENGU','BONK','DOGE','SOL','XRP','ADA','LINK','ETH','BTC','PAXG'];
const TARGETS=[0.2,0.5,1,2];
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
function priceFmt(n){if(!Number.isFinite(Number(n)))return'—';const v=Number(n);return`$${v.toLocaleString('en-US',{minimumFractionDigits:v>=100?2:4,maximumFractionDigits:v>=100?2:8})}`;}
const pct=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const cls=n=>Number(n)>0?'positive':Number(n)<0?'negative':'';
const clamp=(n,min=0,max=1)=>Math.max(min,Math.min(max,n));
const safeCash=b=>Math.max(0,Math.min(Number(b.bankedProfit||0),Number(b.netResult||0)));
const riskLabel=b=>Number(b.maxDrawdownPct||0)>-1?'GREEN':Number(b.maxDrawdownPct||0)>-3?'YELLOW':'RED';
function allBots(){return Object.values(state?.bots||{});}
function scoreBot(b){const bots=allBots();const maxSafe=Math.max(1,...bots.map(safeCash));const maxHarvest=Math.max(1,...bots.map(x=>Number(x.harvestCount||0)));const safeScore=clamp(safeCash(b)/maxSafe);const harvestScore=clamp(Number(b.harvestCount||0)/maxHarvest);const dd=Math.abs(Math.min(0,Number(b.maxDrawdownPct||0)));const riskScore=clamp(1-dd/5);const banked=Number(b.bankedProfit||0),net=Number(b.netResult||0);const stability=banked>0?clamp(1-Math.abs(banked-net)/Math.max(banked,1)):0;return Math.round((safeScore*.40+harvestScore*.25+riskScore*.20+stability*.15)*100);}
function elapsedHours(b){if(!b.startedAt)return 0;return Math.max(0,(Date.now()-new Date(b.startedAt).getTime())/36e5);}
function monthlyRunRate(b,capital){const h=elapsedHours(b);if(h<24)return null;return safeCash(b)/h*24*30*(capital/Number(b.baseCapital||1000));}
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function renderTotals(){const bots=allBots(),capital=bots.reduce((s,b)=>s+Number(b.baseCapital||0),0),banked=bots.reduce((s,b)=>s+Number(b.bankedProfit||0),0),wealth=bots.reduce((s,b)=>s+Number(b.totalWealth||0),0),safe=bots.reduce((s,b)=>s+safeCash(b),0),harvests=bots.reduce((s,b)=>s+Number(b.harvestCount||0),0),net=wealth-capital;$('totalCapital').textContent=money(capital);$('totalBanked').textContent=money(banked);$('totalSafeCash').textContent=money(safe);$('totalWealth').textContent=money(wealth);$('totalHarvests').textContent=`${harvests} harvest${harvests===1?'':'s'}`;$('totalPnL').textContent=`${net>=0?'+':''}${money(net)} vs base`;$('totalPnL').className=cls(net);}
function renderWinners(){$('winnerBody').innerHTML=ASSETS.map(s=>{const variants=TARGETS.map(t=>state.bots[botId(s,t)]);const best=[...variants].sort((a,b)=>b.netResult-a.netResult)[0];return`<tr><td><strong>${s}</strong></td><td><strong>${best.targetPct}%</strong></td><td>${best.harvestCount}</td><td class="positive">${money(best.bankedProfit)}</td><td class="${cls(best.netResult)}"><strong>${money(best.netResult)}</strong></td><td class="${cls(best.maxDrawdownPct)}">${pct(best.maxDrawdownPct)}</td></tr>`;}).join('');}
function renderCashByCrypto(){const rows=ASSETS.map(s=>{const variants=TARGETS.map(t=>state.bots[botId(s,t)]);const best=[...variants].sort((a,b)=>safeCash(b)-safeCash(a)||scoreBot(b)-scoreBot(a)||b.netResult-a.netResult)[0];return{...best,safe:safeCash(best),score:scoreBot(best)};}).sort((a,b)=>b.safe-a.safe||b.score-a.score);$('cashCryptoBody').innerHTML=rows.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}">${money(b.netResult)}</td><td class="positive"><strong>${money(b.safe)}</strong></td><td><strong>${b.score}</strong></td><td>${riskLabel(b)}</td></tr>`).join('');}
function renderCashBots(){const bots=allBots().map(b=>({...b,safe:safeCash(b),score:scoreBot(b)})).sort((a,b)=>b.safe-a.safe||b.score-a.score||b.netResult-a.netResult);$('cashBotBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}">${money(b.netResult)}</td><td class="positive"><strong>${money(b.safe)}</strong></td><td><strong>${b.score}</strong></td><td>${riskLabel(b)}</td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td></tr>`).join('');}
function renderSalary(){const bots=allBots().map(b=>({...b,safe:safeCash(b),score:scoreBot(b)})).sort((a,b)=>b.safe-a.safe||b.score-a.score);const best=bots[0];if(!best){$('salaryBody').innerHTML='';return;}const capitals=[1000,5000,10000,25000,50000];const h=elapsedHours(best);$('salaryLead').textContent=`Leader now: ${best.symbol} ${best.targetPct}% • Safe cash ${money(best.safe)} • Score ${best.score}`;$('salaryBody').innerHTML=capitals.map(c=>{const m=monthlyRunRate(best,c);return`<tr><td>${money(c)}</td><td>${m===null?'Collecting data (<24h)':money(m)}</td></tr>`;}).join('');$('salaryNote').textContent=h<24?'Monthly run-rate unlocks after 24 hours. Early projections would be too noisy.':'Run-rate extrapolates the Safe Cash pace observed so far. It is not a profit guarantee.';}
function renderTargetLeaders(){$('targetBody').innerHTML=TARGETS.map(t=>{const group=ASSETS.map(s=>state.bots[botId(s,t)]);const net=group.reduce((s,b)=>s+b.netResult,0),banked=group.reduce((s,b)=>s+b.bankedProfit,0),safe=group.reduce((s,b)=>s+safeCash(b),0),harvests=group.reduce((s,b)=>s+b.harvestCount,0);return`<tr><td><strong>${t}%</strong></td><td>${harvests}</td><td class="positive">${money(banked)}</td><td class="positive"><strong>${money(safe)}</strong></td><td class="${cls(net)}"><strong>${money(net)}</strong></td></tr>`;}).join('');}
function renderScoreboard(){const bots=allBots().sort((a,b)=>b.netResult-a.netResult);$('scoreBody').innerHTML=bots.map((b,i)=>`<tr><td>${i+1}</td><td><strong>${b.symbol}</strong></td><td><strong>${b.targetPct}%</strong></td><td>${priceFmt(b.currentPrice)}</td><td>${b.harvestCount}</td><td class="positive">${money(b.bankedProfit)}</td><td class="${cls(b.unrealized)}">${money(b.unrealized)}</td><td class="${cls(b.netResult)}"><strong>${money(b.netResult)}</strong></td><td class="positive"><strong>${money(safeCash(b))}</strong></td><td>${scoreBot(b)}</td><td>${riskLabel(b)}</td><td class="${cls(b.maxDrawdownPct)}">${pct(b.maxDrawdownPct)}</td><td>${money(b.totalWealth)}</td></tr>`).join('');}
function render(){if(!state?.bots)return;renderTotals();renderWinners();renderCashByCrypto();renderCashBots();renderSalary();renderTargetLeaders();renderScoreboard();const bots=allBots(),errors=bots.filter(b=>b.lastError);$('liveDot').className=`dot ${errors.length?'':'live'}`;$('liveStatus').textContent=errors.length?`Kraken issue: ${[...new Set(errors.map(b=>b.symbol))].join(', ')}`:'48 paper bots live • 12 Kraken feeds • server 24/7';}
async function refreshState(){try{state=await api('/api/state');render();}catch(e){$('liveDot').className='dot';$('liveStatus').textContent='Server connection lost';}}
$('refreshBtn').addEventListener('click',async()=>{$('refreshBtn').disabled=true;try{state=await api('/api/refresh',{method:'POST',body:'{}'});render();}finally{$('refreshBtn').disabled=false;}});refreshState();setInterval(refreshState,5000);
