const http=require('http'),fs=require('fs'),path=require('path');
const PORT=process.env.PORT||3000;
const STATE_FILE=process.env.STATE_FILE||path.join(__dirname,'paper-state-48bots.json');
const POLL_MS=Math.max(5000,Number(process.env.POLL_MS||15000));
const ASSETS={TRUMP:'TRUMPUSD',WIF:'WIFUSD',PENGU:'PENGUUSD',BONK:'BONKUSD',DOGE:'DOGEUSD',SOL:'SOLUSD',XRP:'XRPUSD',ADA:'ADAUSD',LINK:'LINKUSD',ETH:'ETHUSD',BTC:'XBTUSD',PAXG:'PAXGUSD'};
const TARGETS=[0.2,0.5,1,2];
const botId=(s,t)=>`${s}_${String(t).replace('.','_')}`;
function freshBot(symbol,targetPct){return{id:botId(symbol,targetPct),symbol,pair:ASSETS[symbol],baseCapital:1000,targetPct,feePct:0,currentPrice:null,entryPrice:null,tokensHeld:0,bankedProfit:0,harvestCount:0,running:true,startedAt:null,lastHarvestAt:null,lastUpdated:null,lastError:null,maxDrawdownPct:0,history:[]};}
function defaults(){const bots={};for(const s of Object.keys(ASSETS))for(const t of TARGETS){const b=freshBot(s,t);bots[b.id]=b;}return{bots};}
function load(){try{if(fs.existsSync(STATE_FILE)){const saved=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));if(saved.bots){const bots={};for(const s of Object.keys(ASSETS))for(const t of TARGETS){const f=freshBot(s,t),p=saved.bots[f.id];bots[f.id]=p?{...f,...p,id:f.id,symbol:s,pair:f.pair,targetPct:t}:f;}return{bots};}}}catch(e){console.error('State load failed',e.message);}return defaults();}
let state=load();
function save(){try{fs.writeFileSync(STATE_FILE,JSON.stringify(state,null,2));}catch(e){console.error('State save failed',e.message);}}
const positionValue=b=>b.tokensHeld&&b.currentPrice?b.tokensHeld*b.currentPrice:0;
const targetPrice=b=>b.entryPrice?b.entryPrice*(1+b.targetPct/100):null;
function evaluate(b){if(!b.running||!b.currentPrice)return;if(!b.entryPrice){b.entryPrice=b.currentPrice;b.tokensHeld=b.baseCapital/b.entryPrice;b.startedAt=b.startedAt||new Date().toISOString();return;}const move=((b.currentPrice/b.entryPrice)-1)*100;if(move<b.maxDrawdownPct)b.maxDrawdownPct=move;if(b.currentPrice+Number.EPSILON<targetPrice(b))return;const exitValue=positionValue(b),grossProfit=exitValue-b.baseCapital,fees=(b.baseCapital+exitValue)*(b.feePct/100),netBanked=grossProfit-fees,now=new Date().toISOString();b.bankedProfit+=netBanked;b.harvestCount++;b.lastHarvestAt=now;b.history.push({number:b.harvestCount,time:now,entry:b.entryPrice,exit:b.currentPrice,grossProfit,fees,netBanked,totalBanked:b.bankedProfit});b.entryPrice=b.currentPrice;b.tokensHeld=b.baseCapital/b.entryPrice;}
async function fetchPrice(symbol){const res=await fetch(`https://api.kraken.com/0/public/Ticker?pair=${encodeURIComponent(ASSETS[symbol])}`,{headers:{'user-agent':'crumb-harvester-48/1.0'}});if(!res.ok)throw new Error(`Kraken HTTP ${res.status}`);const data=await res.json();if(data.error?.length)throw new Error(data.error.join(', '));const price=Number(Object.values(data.result||{})[0]?.c?.[0]);if(!Number.isFinite(price)||price<=0)throw new Error(`${symbol}/USD price missing`);return price;}
async function fetchAll(){await Promise.all(Object.keys(ASSETS).map(async s=>{try{const price=await fetchPrice(s);for(const t of TARGETS){const b=state.bots[botId(s,t)];b.currentPrice=price;b.lastUpdated=new Date().toISOString();b.lastError=null;evaluate(b);}}catch(e){for(const t of TARGETS){const b=state.bots[botId(s,t)];b.lastError=e.message;b.lastUpdated=new Date().toISOString();}}}));save();}
function pub(b){const pos=positionValue(b),cycleMovePct=b.entryPrice&&b.currentPrice?((b.currentPrice/b.entryPrice)-1)*100:0,target=targetPrice(b),totalWealth=(b.entryPrice?pos:b.baseCapital)+b.bankedProfit;return{...b,targetPrice:target,positionValue:pos,unrealized:b.entryPrice?pos-b.baseCapital:0,cycleMovePct,distancePct:target&&b.currentPrice?((target/b.currentPrice)-1)*100:null,totalWealth,netResult:totalWealth-b.baseCapital,netResultPct:((totalWealth-b.baseCapital)/b.baseCapital)*100};}
const publicState=()=>({assets:Object.keys(ASSETS),targets:TARGETS,bots:Object.fromEntries(Object.entries(state.bots).map(([id,b])=>[id,pub(b)]))});
function sendJson(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(body);}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname==='/api/health')return sendJson(res,200,{ok:true,botCount:Object.keys(state.bots).length,bots:Object.values(state.bots).map(b=>({id:b.id,running:b.running,lastUpdated:b.lastUpdated,lastError:b.lastError}))});if(url.pathname==='/api/state'&&req.method==='GET')return sendJson(res,200,publicState());if(url.pathname==='/api/refresh'&&req.method==='POST'){await fetchAll();return sendJson(res,200,publicState());}let urlPath=url.pathname==='/'?'index.html':url.pathname.replace(/^[/\\]+/,'');const safePath=path.normalize(urlPath).replace(/^([.][.][/\\])+/,'');const filePath=path.join(__dirname,safePath);if(!filePath.startsWith(__dirname)){res.writeHead(403);return res.end('Forbidden');}fs.readFile(filePath,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':mime[path.extname(filePath)]||'application/octet-stream'});res.end(data);});}catch(e){sendJson(res,500,{error:e.message});}});
server.listen(PORT,()=>console.log(`48 Bot Harvest Lab listening on ${PORT}`));fetchAll();setInterval(fetchAll,POLL_MS);
